[project]
name = "rclip"
version = "2.1.0"
description = "AI-Powered Command-Line Photo Search Tool"
repository = "https://github.com/sabinu/rclip"
authors = [{name="Yurij Mikhalevich", email="yurij@mikhalevi.ch"}]
license = "MIT"
readme = "README.md"
keywords = ["image search", "computer vision", "photography"]
requires-python = ">=3.10"
dependencies = [
    "numpy~=2.1.3",
    "open-clip-torch>=3.1.0",
    "pillow>=12.0.0",
    "pillow-heif>=1.1.1",
    "rawpy>=0.24.0",
    "requests~=2.32",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "tqdm>=4.65.0",
]

[dependency-groups]
dev = [
    "jinja2>=3.1.6",
    "pytest>=9.0.2",
    "ruff>=0.14.11",
    "ty>=0.0.11",
]

[project.scripts]
rclip = "rclip.main:main"

# ----------------------------------------------------------

[build-system]
# https://docs.astral.sh/uv/concepts/build-backend/
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "rclip"
module-root = ""

# ----------------------------------------------------------

[tool.basedpyright]
typeCheckingMode = "basic"
include = ["rclip"]

# ----------------------------------------------------------

[tool.ty.environment]
extra-paths = ["./rclip"]

[tool.ty.rules]
missing-argument = "ignore"

# ----------------------------------------------------------

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # Pyflakes
  "UP",  # pyupgrade
  "B",   # flake8-bugbear
  "S",   # flake8-bandit
  "SIM", # flake8-simplify
  "I",   # isort
  "PL",  # pylint
]
extend-select = [
  "C90", # mccabe - complexity
  "UP",  # pyupgrade
  # "D",   # pydocstyle
]
exclude = ["*.ipynb"]

[tool.ruff.lint.pydocstyle]
convention = "google"
